project_name       = "devgen"
region             = "us-east-1"
github_repo        = "Abdulganiu123/ai-ops-platform"
state_bucket_name  = "bucket-for-devgen-terraform-state"
budget_alert_email = "alert@gmail.com"